spring:
  h2:
    console:
      enabled: true
  datasource:
    password: h2
    username: h2
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver

cron:
  expression: "0 0/10 * * * ?"
server:
  port: 4200